enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)


patches-version = "dev"

[SpotifyOld]
arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
#apkmirror-dlurl = "https://apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
#apkmirror-dpi = "120-640dpi"
build-mode = "apk"
included-patches = "'Custom theme' 'Sanitize sharing links' 'Fix third party launchers widgets'"

[SpotifyA14]
arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
#apkmirror-dlurl = "https://apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
#apkmirror-dpi = "120-640dpi"
build-mode = "apk"
included-patches = "'Custom theme' 'Sanitize sharing links' 'Fix third party launchers widgets'"
patcher-args = "-e 'Custom theme' -ObackgroundColor=@android:color/system_background_dark -ObackgroundColorSecondary=@android:color/system_surface_container_high_dark -OaccentColor=@android:color/system_primary_dark -OaccentColorPressed=@android:color/system_primary_light"

[Reddit]
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Twitter]
enabled = false
build-mode = "apk"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Instagram]
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[GooglePhotos]
enabled= false
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

[YouTube]
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Custom branding' 'Theme'"
patcher-args = "-OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50 "

[Protonmail]
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
build-mode = "apk"